/*
Copyright (c) 2014-2015 WASPP (waspp.org at gmail dot com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <map>
#include <string>

#include <boost/property_tree/ptree.hpp>

// when using both boost asio and boost ptree on win32
// put these lines below before json_parser.hpp
#ifdef _WIN32
#define WIN32_LEAN_AND_MEAN
#endif

#include <boost/property_tree/json_parser.hpp>
#include <boost/foreach.hpp>

#include <boost/lexical_cast.hpp>

#include "logger.hpp"
#include "config.hpp"

namespace waspp
{

	config::config() : expiry_sec(0), update_sec(0), validate_ip(false), validate_ua(false), num_threads(0)
	{
	}

	config::~config()
	{
	}

	bool config::init(const std::string& file, const std::string& server_id)
	{
		logger* log = logger::instance();

		try
		{
			std::ifstream is(file.c_str(), std::ios::in | std::ios::binary);
			if (!is)
			{
				log->fatal("config::file not found");
				return false;
			}

			boost::property_tree::ptree pt;
			read_json(file, pt);

			BOOST_FOREACH(boost::property_tree::ptree::value_type const& item_, pt.get_child(""))
			{
				std::map<std::string, std::string> i;
				BOOST_FOREACH(boost::property_tree::ptree::value_type const& pair_, item_.second)
				{
					i.insert(std::make_pair(pair_.first, pair_.second.get_value<std::string>()));
				}

				cfg_.insert(std::make_pair(item_.first, i));
			}

			std::vector<std::string> keys;
			std::map< std::string, std::map<std::string, std::string> >::iterator found;

			found = cfg_.find("log");
			{
				if (found == cfg_.end())
				{
					log->fatal("config::log not found");
					return false;
				}

				keys.resize(0);
				{
					keys.push_back("level");
					keys.push_back("rotation");
				}

				for (std::size_t i = 0; i < keys.size(); ++i)
				{
					if ((found->second).find(keys[i]) == (found->second).end())
					{
						log->fatal("config::element not found");
						return false;
					}
				}

				level = cfg_.at("log").at("level");
				rotation = cfg_.at("log").at("rotation");
			}

			found = cfg_.find("session");
			{
				if (found == cfg_.end())
				{
					log->fatal("config::session not found");
					return false;
				}

				keys.resize(0);
				{
					keys.push_back("encrypt_key");
					keys.push_back("sess_cookie");
					keys.push_back("expiry_sec");
					keys.push_back("update_sec");
					keys.push_back("validate_ip");
					keys.push_back("validate_ua");
				}

				for (std::size_t i = 0; i < keys.size(); ++i)
				{
					if ((found->second).find(keys[i]) == (found->second).end())
					{
						log->fatal("config::element not found");
						return false;
					}
				}

				encrypt_key = cfg_.at("session").at("encrypt_key");
				sess_cookie = cfg_.at("session").at("sess_cookie");
				expiry_sec = boost::lexical_cast<double>(cfg_.at("session").at("expiry_sec"));
				update_sec = boost::lexical_cast<double>(cfg_.at("session").at("update_sec"));
				validate_ip = boost::lexical_cast<bool>(cfg_.at("session").at("validate_ip"));
				validate_ua = boost::lexical_cast<bool>(cfg_.at("session").at("validate_ua"));
			}

			found = cfg_.find(server_id);
			{
				if (found == cfg_.end())
				{
					log->fatal("config::server_id not found");
					return false;
				}

				keys.resize(0);
				{
					keys.push_back("address");
					keys.push_back("port");
					keys.push_back("doc_root");
					keys.push_back("num_threads");
				}

				for (std::size_t i = 0; i < keys.size(); ++i)
				{
					if ((found->second).find(keys[i]) == (found->second).end())
					{
						log->fatal("config::element not found");
						return false;
					}
				}

				address = cfg_.at(server_id).at("address");
				port = cfg_.at(server_id).at("port");
				doc_root = cfg_.at(server_id).at("doc_root");
				num_threads = boost::lexical_cast<std::size_t>(cfg_.at(server_id).at("num_threads"));
			}

			return true;
		}
		catch (...)
		{
			throw;
		}

		return false;
	}

	std::map<std::string, std::string>& config::get(const std::string& item)
	{
		std::map< std::string, std::map<std::string, std::string> >::iterator found;
		found = cfg_.find(item);

		if (found == cfg_.end())
		{
			throw std::runtime_error("config::get failed");
		}

		return found->second;
	}

} // namespace waspp
