/*
Copyright (c) 2014-2015 WASPP (waspp.org at gmail dot com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#include <boost/lexical_cast.hpp>

#include "dbconn_pool.hpp"

namespace waspp
{

	dbconn_pool::dbconn_pool()
		: port(0), pool_size(0), timeout_sec(0), pool(0)
	{
	}

	dbconn_pool::~dbconn_pool()
	{
	}

	bool dbconn_pool::init_pool(const std::map<std::string, std::string>& cfg)
	{
		std::vector<std::string> keys;
		{
			keys.push_back("host");
			keys.push_back("userid");
			keys.push_back("passwd");
			keys.push_back("database");
			keys.push_back("port");
			keys.push_back("pool_size");
			keys.push_back("timeout_sec");
		}

		for (std::size_t i = 0; i < keys.size(); ++i)
		{
			if (cfg.find(keys[i]) == cfg.end())
			{
				return false;
			}
		}

		host = cfg.at("host");
		userid = cfg.at("userid");
		passwd = cfg.at("passwd");
		database = cfg.at("database");

		port = boost::lexical_cast<unsigned int>(cfg.at("port"));
		pool_size = boost::lexical_cast<std::size_t>(cfg.at("pool_size"));
		timeout_sec = boost::lexical_cast<double>(cfg.at("timeout_sec"));

		return true;
	}

	bool dbconn_pool::fill_pool()
	{
		if (pool_size == 0)
		{
			return false;
		}

		for (std::size_t i = 0; i < pool_size; ++i)
		{
			dbconn_ptr dbconn = connect();
			if (!validate(dbconn))
			{
				return false;
			}

			pool.push_back(dbconn);
		}

		return true;
	}

	dbconn_ptr dbconn_pool::get_dbconn()
	{
		lock.acquire();
		//{
			if (pool.empty())
			{
				lock.release();
				return connect(false);
			}

			dbconn_ptr dbconn = *(pool.end() - 1);
			pool.pop_back();
		//}
		lock.release();

		double diff = std::difftime(std::time(0), mktime(dbconn->last_released()));

		if (diff > timeout_sec && !validate(dbconn))
		{
			return connect();
		}

		return dbconn;
	}

	void dbconn_pool::free_dbconn(dbconn_ptr dbconn)
	{
		if (!dbconn->is_pooled())
		{
			return;
		}

		std::time_t time_ = std::time(0);
		dbconn->set_released(*std::localtime(&time_));

		lock.acquire();
		{
			pool.push_back(dbconn);
		}
		lock.release();
	}

	dbconn_ptr dbconn_pool::connect(bool pooled_)
	{
		return dbconn_ptr(new mysqlpp::connection(host.c_str(), userid.c_str(), passwd.c_str(), database.c_str(), port, pooled_));
	}

	bool dbconn_pool::validate(dbconn_ptr dbconn)
	{
		try
		{
			boost::scoped_ptr<mysqlpp::statement> stmt(dbconn->prepare("DO 0"));
			stmt->execute();

			return true;
		}
		catch (...)
		{

		}

		return false;
	}

} // namespace waspp
