/*
Copyright (c) 2014-2015 WASPP (waspp.org at gmail dot com)
Copyright (c) 2003-2012 Christopher M. Kohlhoff (chris at kohlhoff dot com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

//
// Copyright (c) 2003-2012 Christopher M. Kohlhoff (chris at kohlhoff dot com)
//
// Distributed under the Boost Software License, Version 1.0. (See accompanying
// file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)
//

#include <iostream>
#include <sstream>
#include <map>
#include <string>

#include <boost/asio.hpp>
#include <boost/bind.hpp>

#include "logger.hpp"
#include "config.hpp"
#include "database.hpp"
#include "server.hpp"

int main(int argc, char* argv[])
{
	waspp::logger* log = waspp::logger::instance();
	waspp::config* cfg = waspp::config::instance();
	waspp::database* db = waspp::database::instance();

	try
	{
		//if (0)
		if (argc != 3)
		{
			std::cerr << "Usage: ./waspp develop 00 &\n";
			return 1;
		}

		std::ostringstream oss;
		std::string log_file, cfg_file, server_id;
		//if (0)
		{
			oss.str(std::string());
			oss << "../log/" << argv[1] << argv[2] << ".csv";
			log_file.append(oss.str());

			oss.str(std::string());
			oss << "../cfg/" << argv[1] << ".json";
			cfg_file.append(oss.str());

			oss.str(std::string());
			oss << "server" << argv[2];
			server_id.append(oss.str());
		}
		//log_file.append("../log/develop.csv");
		//cfg_file.append("../cfg/develop.json");
		//server_id.append("server00");

		log->file(log_file);

		if (!cfg->init(cfg_file, server_id))
		{
			log->fatal("config::init failed");
			return 1;
		}

		if (!log->init(cfg->level, cfg->rotation))
		{
			log->fatal("logger::init failed");
			return 1;
		}

		std::vector<std::string> dbkeys;
		{
			dbkeys.push_back("db_index");
			dbkeys.push_back("db_000");
			dbkeys.push_back("db_001");
			dbkeys.push_back("db_etc");
		}

		if (!db->init(cfg, dbkeys))
		{
			log->fatal("database::init failed");
			return 1;
		}

		log->info("waspp starting..");

		waspp::server s(cfg->address, cfg->port, cfg->doc_root, cfg->num_threads);
		s.run();

		log->info("waspp stopped");
	}
	catch (std::exception& e)
	{
		log->fatal(e.what());
		return 1;
	}

	return 0;
}
