/*
Copyright (c) 2014-2015 WASPP (waspp.org at gmail dot com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef WASPP_SESSION_HPP
#define WASPP_SESSION_HPP

#include <map>
#include <string>

#include <boost/serialization/serialization.hpp>
#include <boost/serialization/map.hpp>
#include <boost/archive/text_iarchive.hpp>
#include <boost/archive/text_oarchive.hpp>

#include "config.hpp"
#include "logger.hpp"
#include "request.hpp"
#include "response.hpp"

namespace waspp
{

	class session
	{
	public:
		session(config* cfg_, logger* log_, request* req_, response* res_);
		~session();

		std::string& get_sess(const std::string& name);
		void set_sess(const std::string& name, const std::string& value);

	private:
		bool load();

		void create();
		void update();

		std::string get_uuid();

		std::string get_curr_tm();
		std::time_t get_last_tm();

		std::string get_curr_ip();
		std::string get_last_ip();

		std::string get_curr_ua();
		std::string get_last_ua();

		void serialize_and_set();

		config* cfg;
		logger* log;
		request* req;
		response* res;
		utility::md5 md5_;

		std::map<std::string, std::string> session_;

	};

} // namespace waspp

#endif // WASPP_SESSION_HPP
