/*
Copyright (c) 2014-2015 WASPP (waspp.org at gmail dot com)

Permission is hereby granted, free of charge, to any person or organization
obtaining a copy of the software and accompanying documentation covered by
this license (the "Software") to use, reproduce, display, distribute,
execute, and transmit the Software, and to prepare derivative works of the
Software, and to permit third-parties to whom the Software is furnished to
do so, all subject to the following:

The copyright notices in the Software and this entire statement, including
the above license grant, this restriction and the following disclaimer,
must be included in all copies of the Software, in whole or in part, and
all derivative works of the Software, unless such copies or derivative
works are solely in the form of machine-executable object code generated by
a source language processor.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE, TITLE AND NON-INFRINGEMENT. IN NO EVENT
SHALL THE COPYRIGHT HOLDERS OR ANYONE DISTRIBUTING THE SOFTWARE BE LIABLE
FOR ANY DAMAGES OR OTHER LIABILITY, WHETHER IN CONTRACT, TORT OR OTHERWISE,
ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
*/

#ifndef WASPP_UTILITY_HPP
#define WASPP_UTILITY_HPP

#include <cstdlib>

#include <openssl/md5.h>

#include <string>

#include <boost/atomic.hpp>
#include <boost/thread.hpp>

namespace waspp
{

	namespace utility
	{

		class spinlock
		{
		public:
			void acquire()
			{
				while (atomic_flag_.test_and_set(boost::memory_order_acquire))
				{
				}
			}

			void release()
			{
				atomic_flag_.clear(boost::memory_order_release);
			}

		private:
			boost::atomic_flag atomic_flag_;

		};
		
		template<typename T>
		class singleton
		{
		public:
			static T* instance()
			{
				if (instance_ != 0)
				{
					return instance_;
				}

				// double checked locking for thread-safe singleton
				lock.acquire();
				if (instance_ == 0)
				{
					instance_ = new T();
					
					// avoid memory leak
					atexit(destory);
				}
				lock.release();

				return instance_;
			}

		protected:
			singleton() {};
			virtual ~singleton() {};

		private:
			static void destory()
			{
				delete instance_;
			}

			static T* instance_;
			static spinlock lock;

		};

		template<typename T> T* singleton<T>::instance_ = 0;
		template<typename T> spinlock singleton<T>::lock;

		class md5
		{
		public:
			md5() {};
			~md5() {};

			std::string digest(const std::string& str_)
			{
				unsigned char digest_[16];
				char* c_str_ = const_cast<char*>(str_.c_str());

				MD5_CTX ctx;
				MD5_Init(&ctx);
				MD5_Update(&ctx, c_str_, strlen(c_str_));
				MD5_Final(digest_, &ctx);

				char md_str[33];
				for (int i = 0; i < 16; ++i)
				{
					sprintf(&md_str[i * 2], "%02x", (unsigned int)digest_[i]);
				}

				return std::string(md_str);
			}

		private:

		};

	} // namespace utility

} // namespace waspp

#endif // WASPP_UTILITY_HPP
